package org.f14a.fatin2.util;

import java.util.HashMap;
import java.util.Map;

public enum Faces {
    SURPRISED(0, "惊讶"),
    POUTING(1, "撅嘴"),
    HORNY(2, "色"),
    DAZE(3, "发呆"),
    SMIRKING(4, "得意"),
    TEARFUL(5, "流泪"),
    SHY(6, "害羞"),
    SILENT(7, "闭嘴"),
    SLEEPING(8, "睡"),
    CRYING(9, "大哭"),
    AWKWARD(10, "尴尬"),
    ANGRY(11, "发怒"),
    PLAYFUL(12, "调皮"),
    GRINNING(13, "呲牙"),
    SMILING(14, "微笑"),
    SAD(15, "难过"),
    COOL(16, "酷"),
    FRANTIC(18, "抓狂"),
    VOMITING(19, "吐"),
    SNICKERING(20, "偷笑"),
    CUTE(21, "可爱"),
    ROLLING_EYES(22, "白眼"),
    ARROGANT(23, "傲慢"),
    HUNGRY(24, "饥饿"),
    SLEEPY(25, "困"),
    PANICKED(26, "惊恐"),
    SWEATING(27, "流汗"),
    SILLY_SMILE(28, "憨笑"),
    LEISURELY(29, "悠闲"),
    STRIVING(30, "奋斗"),
    CURSING(31, "咒骂"),
    QUESTIONING(32, "疑问"),
    SHUSHING(33, "嘘"),
    DIZZY(34, "晕"),
    DECAYING(36, "衰"),
    SKULL(37, "骷髅"),
    HITTING(38, "敲打"),
    GOODBYE_WAVE(39, "再见"),
    SHIVERING(41, "发抖"),
    LOVE(42, "爱情"),
    JUMPING(43, "跳跳"),
    PIG_HEAD(46, "猪头"),
    HUG(49, "拥抱"),
    CAKE(53, "蛋糕"),
    KNIFE(56, "刀"),
    POOP(59, "便便"),
    COFFEE(60, "咖啡"),
    ROSE(63, "玫瑰"),
    WITHERED_ROSE(64, "凋谢"),
    HEART(66, "爱心"),
    BROKEN_HEART(67, "心碎"),
    SUN(74, "太阳"),
    MOON(75, "月亮"),
    THUMBS_UP(76, "赞"),
    STEPPING_ON(77, "踩"),
    HANDSHAKE(78, "握手"),
    VICTORY_SIGN(79, "胜利"),
    FLYING_KISS(85, "飞吻"),
    ANNOYED(86, "怄火"),
    WATERMELON(89, "西瓜"),
    COLD_SWEAT(96, "冷汗"),
    WIPING_SWEAT(97, "擦汗"),
    NOSE_PICKING(98, "抠鼻"),
    CLAPPING_HANDS(99, "鼓掌"),
    EMBARRASSED(100, "糗大了"),
    MISCHIEVOUS_SMILE(101, "坏笑"),
    LEFT_HUMMING(102, "左哼哼"),
    RIGHT_HUMMING(103, "右哼哼"),
    YAWNING(104, "哈欠"),
    DESPISING(105, "鄙视"),
    WRONGED(106, "委屈"),
    ABOUT_TO_CRY(107, "快哭了"),
    SNEERING(108, "阴险"),
    LEFT_KISSING(109, "左亲亲"),
    SCARED(110, "吓"),
    PITIFUL(111, "可怜"),
    KITCHEN_KNIFE(112, "菜刀"),
    BASKETBALL(114, "篮球"),
    SHOWING_LOVE(116, "示爱"),
    FOLDED_HANDS(118, "抱拳"),
    FINGER_HOOK(119, "勾引"),
    FIST(120, "拳头"),
    THUMBS_DOWN(121, "差劲"),
    NO_SIGN(123, "no"),
    OK_SIGN(124, "OK"),
    SPINNING(125, "转圈"),
    WAVING_HAND(129, "挥手"),
    FIRECRACKER(137, "鞭炮"),
    CHEERING(144,"喝彩"),
    SWOLLEN_VEIN(146, "爆筋"),
    LOLLIPOP(147, "棒棒糖"),
    PISTOL(169, "手枪"),
    TEA(171, "茶"),
    ALPACA(185, "羊驼"),
    GHOST(187, "幽灵"),
    BLINKING_EYES(172, "眨眼睛"),
    TEARS_STREAMING(173, "泪奔"),
    HELPLESS(174, "无奈"),
    ACTING_CUTE(175, "卖萌"),
    LITTLE_STRUGGLE(176, "小纠结"),
    SPURTING_BLOOD(177, "喷血"),
    SQUINTING_SMILE(178, "眯眼笑"),
    DOGE(179, "doge"),
    HARASSMENT(181, "骚扰"),
    CRYING_LAUGHING(182, "笑哭"),
    I_AM_THE_PRETTIEST(183, "我最美"),
    LIKING(201, "点赞"),
    CHEEK_RESTING(212, "托腮"),
    HEADACHE(262, "脑阔疼"),
    WEATHERED(263, "沧桑"),
    FACE_PALM(264, "捂脸"),
    EYE_HURTING(265, "辣眼睛"),
    OH_YO(266, "哦哟"),
    BALDNESS(267, "头秃"),
    QUESTIONING_FACE(268, "问号脸"),
    DEEPLY_WATCHING(269, "暗中观察"),
    EMM(270, "emm"),
    MELON_EATING(271, "吃瓜"),
    HEHE_DA(272, "呵呵哒"),
    I_AM_JEALOUS(273, "我酸了"),
    WANG_WANG(277, "汪汪"),
    EYELESS_SMILE(281, "无眼笑"),
    SALUTING(282, "敬礼"),
    LAUGHING_WILDLY(283, "狂笑"),
    EXPRESSIONLESS(284, "面无表情"),
    SLACKING_OFF(285, "摸鱼"),
    DEVILISH_SMILE(286, "魔鬼笑"),
    OH(287, "哦"),
    EYES_WIDE_OPEN(289, "睁眼"),
    TOUCHING_KOI(293, "摸锦鲤"),
    ANTICIPATION(294, "期待"),
    BOWING_THANKS(297, "拜谢"),
    GOLD_INGOT(298, "元宝"),
    AWESOME_BULL(299, "牛啊"),
    GAINED_THREE_JIN(300, "胖三斤"),
    LEFT_NEW_YEAR_GREETING(302, "左拜年"),
    RIGHT_NEW_YEAR_GREETING(303, "右拜年"),
    RIGHT_KISSING(305, "右亲亲"),
    POWERFUL_AS_A_BULL(306, "牛气冲天"),
    MEOW_MEOW(307, "喵喵"),
    CALLS(311, "打call"),
    BIAN_XING(312, "变形"),
    ANALYSIS(314, "仔细分析"),
    VEGETABLE_DOG(317, "菜汪"),
    WORSHIP(318, "崇拜"),
    TAKE_HEART(319, "比心"),
    CHEER_UP(320, "庆祝"),
    DISLIKE(323, "嫌弃"),
    CANDY_EATING(324, "吃糖"),
    FRIGHTENED(325, "惊吓"),
    ANGRY_(326, "生气"),
    PLACARD(332, "举牌牌"),
    FIREWORKS(333, "烟花"),
    HU_HU_SHENG_WEI(334, "虎虎生威"),
    BAO_FU(336, "豹富"),
    FLOWER_FACE(337, "花朵脸"),
    WO_XIANG_KAI_LE(338, "我想开了"),
    EYE_CANDY(339, "舔屏"),
    CIAO(341, "打招呼"),
    SUAN_Q(342, "酸Q"),
    WO_FANG_LE(343, "我方了"),
    YUAN_ZHONG(344, "怨种"),
    RED_PACKET_DUO_DUO(345, "红包多多"),
    NI_ZHEN_BANG(346, "你真棒棒"),
    DA_ZHAN_HONG_TU(347, "大展宏兔"),
    STRONG(349, "坚强"),
    TIE_TIE(350, "贴贴"),
    KNOCK(351, "敲敲"),
    YI(352, "咦"),
    REQUEST(353, "拜托"),
    ZUN_DU_JIA_DU(354, "尊嘟假嘟"),
    YE(355, "耶"),
    SIX_SIX_SIX(356, "666"),
    CRACKED(357, "裂开"),
    CONTINUATION_MARK(424, "续标识"),
    SPARE_ME(425, "求放过"),
    PLAY_WITH_FIRE(426, "玩火"),
    SUSPICIOUS(427, "偷感"),
    I_GOT_IT(428, "收到"),
    HAPPY_SNAKE_YEAR(429, "蛇年快乐");

    private final int slot;
    private final String meaning;
    Faces(int slot, String meaning) {
        this.slot = slot;
        this.meaning = meaning;
    }
    public int slot() {
        return this.slot;
    }
    public String meaning() {
        return this.meaning;
    }

    private static final Map<Integer, Faces> SLOT_INDEX = new HashMap<>();
    static {
        for (Faces face : Faces.values()) {
            SLOT_INDEX.put(face.slot(), face);
        }
    }
    public static Faces fromSlot(int slot) {
        return SLOT_INDEX.get(slot);
    }
    public static String meaningOf(int slot) {
        Faces face = fromSlot(slot);
        return face != null ? face.meaning() : "Unknown";
    }
}
